name = "blog"

[build]
  command = "curl -L https://github.com/getzola/zola/releases/download/v0.18.0/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz | tar xz && ./zola build"
  pages_build_output_dir = "./public" 
