name = "blog"

[build]
  command = "curl -L https://github.com/getzola/zola/releases/download/v0.18.0/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz | tar xz && ./zola build"
  directory = "./public" 

[deploy]
  command = "npx wrangler pages deploy ./public"

